FROM golang:1.23 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /mock ./cmd/mock-jolokia

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /mock /mock
USER 65532:65532
ENTRYPOINT ["/mock"]
